### ISSUE TITLE
Skipping shipping step when logged in

### ISSUE THREAD

**Issue by PascalBrouwers** [danslo/CleanCheckoutTheme#3]
@danslo Why is this piece in email.js?
```
        navigateToNextStep: function () {
            if (this.validateEmail()) {
                stepNavigator.next();
            } else {
                $(this.loginFormSelector + ' input[name=username]').focus();
            }
        }
```

Currently if you are logged in, you will skip the shipping step because of this.

**Comment by danslo** [comment]
Because email is the first step, so a logged in user should skip the email step (and go to shipping).

Not sure why it doesn't do that for you.

**Comment by PascalBrouwers** [comment]
Maybe add something like this?
```
var currentStep = stepNavigator.getActiveItemIndex();
if (this.validateEmail() && stepNavigator.steps()[currentStep].code == 'email') {
```

**Comment by PascalBrouwers** [comment]
Yes, this seems to fix the second skip for me.

**Comment by danslo** [comment]
Still weird that code from email.js (navigateToNextStep) is executing in your shipping step.

**Comment by PascalBrouwers** [comment]
¯\_(ツ)_/¯
Can you add it?
