### ISSUE TITLE
Virtual products 2.2.9

### ISSUE THREAD

**Issue by BrentRobert** [danslo/CleanCheckoutTheme#5]
Hi,
After upgrading to 2.2.9 my shop has the following issue:
When having a virtual quote (logged in) and proceeding to the checkout it loads the payment step. But it tries to redirect to the email step, which is not visible due to the customer being logged in. After that it tries to redirect to the shipping step, which is invalid, since it's a virtual quote. Then it redirects to a checkout/noroute. 

I fixed this by disabling the 'email' step for logged in users, although I'm not sure if this is the correct fix for this issue.

**Comment by edward-simpson** [comment]
Hi Brent,

Sorry it's taken so long for anyone to get back to you, we've just taken over maintenance of this, and will be supporting officially supported Magento versions, unfortunately 2.2.9 is not one of these.  If this is still occurring after upgrading to 2.3+ please let us know
